import {
  ClarityInfo,
  EventTemplate,
  Leader,
  MinistryEvent,
  Parent,
  SmallGroup,
  Student,
  Task,
} from '../types';

export const EVENTS: MinistryEvent[] = [];
export const TASKS: Task[] = [];
export const STUDENTS: Student[] = [];
export const PARENTS: Parent[] = [];
export const LEADERS: Leader[] = [];
export const SMALL_GROUPS: SmallGroup[] = [];

// ---------- Event templates ----------

const PARENT_FACING_FIELDS: (keyof ClarityInfo)[] = [
  'date', 'time', 'dropOffLocation', 'pickUpTime', 'cost',
  'foodInfo', 'forms', 'contactPerson', 'transportation', 'packingList',
];

export const TEMPLATES: EventTemplate[] = [
  {
    id: 'tpl-weekly',
    parentFacing: true,
    name: 'Weekly Youth Group',
    description: 'The weekly rhythm — message, worship, games, small groups.',
    category: 'high-school',
    leadTimeWeeks: 1,
    defaultChecklist: ['Message prepped', 'Worship set confirmed', 'Game planned + supplies', 'Snacks purchased', 'Small group questions to leaders', 'Check-in team confirmed'],
    clarityFields: ['date', 'time', 'dropOffLocation', 'pickUpTime', 'contactPerson'],
    typicalVolunteers: ['Check-in (2)', 'Small group leaders (4–6)', 'Snack team (2)'],
  },
  {
    id: 'tpl-camp',
    parentFacing: true,
    name: 'Camp',
    description: 'Multi-day overnight camp. The biggest lift of the year.',
    category: 'camps-trips',
    leadTimeWeeks: 16,
    defaultChecklist: ['Camp contract + deposit', 'Registration page live', 'Health + liability forms', 'Scholarship process', 'Counselor recruitment', 'Cabin assignments', 'Transportation booked', 'Packing list to parents', 'Payment deadlines communicated', 'Emergency contact sheet printed'],
    clarityFields: PARENT_FACING_FIELDS,
    typicalVolunteers: ['Counselors (1 per 6 students)', 'Nurse/medic (1)', 'Drivers (4–8)'],
  },
  {
    id: 'tpl-retreat',
    parentFacing: true,
    name: 'Retreat',
    description: 'Weekend getaway — lighter than camp, same parent-info needs.',
    category: 'camps-trips',
    leadTimeWeeks: 10,
    defaultChecklist: ['Venue booked', 'Registration live', 'Forms collected', 'Speaker/curriculum chosen', 'Meal plan', 'Transportation plan', 'Packing list sent'],
    clarityFields: PARENT_FACING_FIELDS,
    typicalVolunteers: ['Cabin leaders', 'Kitchen team', 'Drivers'],
  },
  {
    id: 'tpl-lake-day',
    parentFacing: true,
    name: 'Lake Day',
    description: 'Single-day water event. Waivers and supervision are the big rocks.',
    category: 'camps-trips',
    leadTimeWeeks: 6,
    defaultChecklist: ['Site/permit reserved', 'Liability waivers posted', 'Driver list + insurance', 'Lifeguard coverage', 'Food plan', 'Sunscreen + first aid', 'Parent info email'],
    clarityFields: PARENT_FACING_FIELDS,
    typicalVolunteers: ['Drivers (6–10)', 'Lifeguard-certified adults (2)', 'Grill team (2)'],
  },
  {
    id: 'tpl-parent-meeting',
    parentFacing: true,
    name: 'Parent Meeting',
    description: 'Info night for parents — slides, FAQ handout, childcare.',
    category: 'parents',
    leadTimeWeeks: 4,
    defaultChecklist: ['Date on church calendar', 'Slide deck', 'FAQ handout printed', 'RSVP form', 'Childcare arranged', 'Reminder email + text'],
    clarityFields: ['date', 'time', 'contactPerson'],
    typicalVolunteers: ['Childcare (2)'],
  },
  {
    id: 'tpl-leader-meeting',
    parentFacing: false,
    name: 'Leader Meeting',
    description: 'Vision, calendar, and care for your volunteer team.',
    category: 'leaders',
    leadTimeWeeks: 2,
    defaultChecklist: ['Agenda drafted', 'Food ordered', 'Calendar handout', 'One appreciation moment planned'],
    clarityFields: ['date', 'time', 'contactPerson'],
    typicalVolunteers: [],
  },
  {
    id: 'tpl-service-project',
    parentFacing: true,
    name: 'Service Project',
    description: 'Hands-on serve day with a local partner organization.',
    category: 'high-school',
    leadTimeWeeks: 5,
    defaultChecklist: ['Partner org confirmed', 'Waivers if off-site', 'Supplies list', 'Transportation plan', 'Parent email with details'],
    clarityFields: PARENT_FACING_FIELDS,
    typicalVolunteers: ['Adult leaders (1 per 8)', 'Drivers'],
  },
  {
    id: 'tpl-fundraiser',
    parentFacing: true,
    name: 'Fundraiser',
    description: 'Raise money for camp or missions — clear goal, clear ask.',
    category: 'promo',
    leadTimeWeeks: 6,
    defaultChecklist: ['Goal + use of funds defined', 'Date on church calendar', 'Promo plan (announcement, slides, social)', 'Student sign-ups', 'Cash handling plan', 'Thank-you follow-up'],
    clarityFields: ['date', 'time', 'cost', 'contactPerson'],
    typicalVolunteers: ['Setup team', 'Cash handlers (2 adults)'],
  },
  {
    id: 'tpl-tribe-night',
    parentFacing: true,
    name: 'Tribe Night',
    description: 'High-energy competition night. Bring-a-friend culture builder.',
    category: 'high-school',
    leadTimeWeeks: 4,
    defaultChecklist: ['Tribe rosters', 'Station games chosen', 'Supplies purchased', 'Promo video', 'Station leaders briefed', 'Prizes'],
    clarityFields: ['date', 'time', 'dropOffLocation', 'pickUpTime', 'foodInfo', 'contactPerson'],
    typicalVolunteers: ['Station leaders (6)', 'Check-in (2)', 'Photographer (1)'],
  },
  {
    id: 'tpl-bible-study',
    parentFacing: false,
    name: 'Bible Study',
    description: 'Recurring deep-dive study, usually off-campus.',
    category: 'bible-study',
    leadTimeWeeks: 2,
    defaultChecklist: ['Passage/curriculum chosen', 'Location reserved', 'Reading plan sent', 'Co-leader confirmed'],
    clarityFields: ['date', 'time', 'contactPerson'],
    typicalVolunteers: ['Co-leader (1)'],
  },
  {
    id: 'tpl-mission-trip',
    parentFacing: true,
    name: 'Mission Trip',
    description: 'The longest runway in youth ministry — passports, funds, training.',
    category: 'camps-trips',
    leadTimeWeeks: 26,
    defaultChecklist: ['Partner org + dates confirmed', 'Interest meeting', 'Passport check', 'Deposit schedule', 'Support letter template', 'Fundraisers scheduled', 'Team training nights (3)', 'Travel insurance', 'Emergency protocol + contacts', 'Commissioning Sunday'],
    clarityFields: PARENT_FACING_FIELDS,
    typicalVolunteers: ['Adult leaders (1 per 4)', 'Trip nurse', 'Prayer team'],
  },
  {
    id: 'tpl-graduation',
    parentFacing: true,
    name: 'Graduation Night',
    description: 'Honor the seniors — slideshow, blessings, send-off.',
    category: 'high-school',
    leadTimeWeeks: 6,
    defaultChecklist: ['Senior list confirmed', 'Photo slideshow', 'Leader blessing assignments', 'Gifts ordered', 'Parent invitations', 'Dessert plan'],
    clarityFields: ['date', 'time', 'foodInfo', 'contactPerson'],
    typicalVolunteers: ['Slideshow editor', 'Dessert team'],
  },
];
