import {
  ChecklistItem,
  ClarityInfo,
  EventTemplate,
  Leader,
  MinistryEvent,
  Parent,
  SmallGroup,
  Student,
  Task,
} from '../types';

// Mock data is dated relative to "today" so the dashboard always has a live week.

const pad = (n: number) => String(n).padStart(2, '0');

function day(offset: number, hour = 9, minute = 0): string {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(hour)}:${pad(minute)}`;
}

function checklist(prefix: string, items: [string, boolean][]): ChecklistItem[] {
  return items.map(([label, done], i) => ({ id: `${prefix}-${i + 1}`, label, done }));
}

function clarity(overrides: Partial<ClarityInfo> = {}): ClarityInfo {
  return {
    date: true,
    time: true,
    dropOffLocation: true,
    pickUpTime: true,
    cost: true,
    foodInfo: true,
    forms: true,
    contactPerson: true,
    transportation: true,
    packingList: true,
    ...overrides,
  };
}

// ---------- Events ----------

export const EVENTS: MinistryEvent[] = [
  {
    id: 'hs-youth',
    title: 'High School Youth',
    category: 'high-school',
    start: day(0, 19, 0),
    location: 'The Barn',
    targetGroup: 'High school students (9th–12th)',
    status: 'confirmed',
    parentFacing: true,
    registered: 38,
    volunteers: [
      { role: 'Check-in', needed: 2, confirmed: 2 },
      { role: 'Small group leaders', needed: 6, confirmed: 5 },
      { role: 'Snack team', needed: 2, confirmed: 1 },
    ],
    forms: 'na',
    payments: 'na',
    transportation: 'na',
    parentComm: 'complete',
    checklist: checklist('hs-youth', [
      ['Message + slides finalized', true],
      ['Worship set confirmed with Hannah', true],
      ['Game supplies pulled from closet', true],
      ['Snacks purchased', false],
      ['Small group questions sent to leaders', true],
    ]),
    clarity: clarity({ packingList: false }),
    notes: 'Series: "Unshakeable" week 3. Dave is out — need a fill-in for the grill.',
  },
  {
    id: 'ms-youth',
    title: 'Middle School Youth',
    category: 'middle-school',
    start: day(1, 18, 30),
    location: 'Youth Room',
    targetGroup: 'Middle school students (6th–8th)',
    status: 'confirmed',
    parentFacing: true,
    registered: 26,
    volunteers: [
      { role: 'Check-in', needed: 2, confirmed: 2 },
      { role: 'Small group leaders', needed: 4, confirmed: 4 },
      { role: 'Games lead', needed: 1, confirmed: 0 },
    ],
    forms: 'na',
    payments: 'na',
    transportation: 'na',
    parentComm: 'complete',
    checklist: checklist('ms-youth', [
      ['Message prepped', true],
      ['Game: 9-square set up plan', false],
      ['Pick-up reminder text scheduled', true],
    ]),
    clarity: clarity({ packingList: false }),
    notes: 'New student Caleb visiting again — make sure he gets connected to a group.',
  },
  {
    id: 'bible-study',
    title: 'Midweek Bible Study',
    category: 'bible-study',
    start: day(6, 7, 0),
    location: 'Common Grounds Coffee',
    targetGroup: 'HS students (open invite)',
    status: 'confirmed',
    parentFacing: false,
    registered: 11,
    volunteers: [{ role: 'Co-leader', needed: 1, confirmed: 1 }],
    forms: 'na',
    payments: 'na',
    transportation: 'na',
    parentComm: 'na',
    checklist: checklist('bible-study', [
      ['Reading plan sent (James 3)', true],
      ['Reserve back table', true],
    ]),
    clarity: clarity({ packingList: false, foodInfo: false }),
  },
  {
    id: 'tribe-night',
    title: 'Tribe Night',
    category: 'high-school',
    start: day(9, 19, 0),
    location: 'The Barn + back field',
    targetGroup: 'MS + HS combined',
    status: 'promoting',
    parentFacing: true,
    registered: 22,
    capacity: 80,
    volunteers: [
      { role: 'Station leaders', needed: 6, confirmed: 3 },
      { role: 'Check-in', needed: 2, confirmed: 1 },
      { role: 'Photographer', needed: 1, confirmed: 0 },
    ],
    forms: 'na',
    payments: 'na',
    transportation: 'na',
    parentComm: 'in-progress',
    checklist: checklist('tribe-night', [
      ['Tribe rosters drafted', true],
      ['Station games chosen', true],
      ['Supplies list to shopping', false],
      ['Promo video at youth group', false],
      ['Color powder ordered', false],
    ]),
    clarity: clarity({ pickUpTime: false, foodInfo: false, packingList: false, transportation: false }),
    notes: 'Big push night — students bring friends. Need the pick-up time in the parent email this week.',
  },
  {
    id: 'lake-day',
    title: 'Lake Day',
    category: 'camps-trips',
    start: day(17, 10, 0),
    location: 'Elk Lake — Day Use Area',
    targetGroup: 'MS + HS students',
    status: 'registration-open',
    parentFacing: true,
    registered: 31,
    capacity: 60,
    volunteers: [
      { role: 'Drivers', needed: 8, confirmed: 5 },
      { role: 'Lifeguard-certified adult', needed: 2, confirmed: 1 },
      { role: 'Grill team', needed: 2, confirmed: 2 },
    ],
    forms: 'in-progress',
    payments: 'in-progress',
    transportation: 'in-progress',
    parentComm: 'in-progress',
    checklist: checklist('lake-day', [
      ['Day-use permit reserved', true],
      ['Liability waivers posted', true],
      ['Driver list + insurance check', false],
      ['Food plan (burgers + sides)', false],
      ['Sunscreen + first aid restocked', false],
      ['Parent info email drafted', false],
    ]),
    clarity: clarity({ pickUpTime: false, foodInfo: false, packingList: false }),
    notes: '$10/student covers food + gas. 12 waivers still missing.',
  },
  {
    id: 'leader-lunch',
    title: 'Leader Lunch',
    category: 'leaders',
    start: day(4, 12, 30),
    location: 'Fellowship Hall',
    targetGroup: 'All youth leaders',
    status: 'confirmed',
    parentFacing: false,
    registered: 9,
    volunteers: [],
    forms: 'na',
    payments: 'na',
    transportation: 'na',
    parentComm: 'na',
    checklist: checklist('leader-lunch', [
      ['Agenda: summer calendar walkthrough', true],
      ['Order tacos', false],
      ['Print camp volunteer sign-up sheet', false],
    ]),
    clarity: clarity({ packingList: false, transportation: false, dropOffLocation: false }),
    notes: 'Main goal: fill the last 2 camp counselor spots in the room.',
  },
  {
    id: 'parent-meeting',
    title: 'Summer Trips Parent Meeting',
    category: 'parents',
    start: day(11, 18, 0),
    location: 'Sanctuary',
    targetGroup: 'Parents of camp + mission trip students',
    status: 'promoting',
    parentFacing: true,
    registered: 14,
    capacity: 100,
    volunteers: [{ role: 'Childcare', needed: 2, confirmed: 2 }],
    forms: 'na',
    payments: 'na',
    transportation: 'na',
    parentComm: 'in-progress',
    checklist: checklist('parent-meeting', [
      ['Slide deck: camp + mission trip details', false],
      ['Printed FAQ handout', false],
      ['RSVP form live', true],
      ['Reminder email scheduled', true],
    ]),
    clarity: clarity({ packingList: false, transportation: false }),
    notes: 'This meeting is where most camp questions get answered — push attendance hard.',
  },
  {
    id: 'summer-camp',
    title: 'Summer Camp — Camp Tadmor',
    category: 'camps-trips',
    start: day(32, 8, 0),
    location: 'Camp Tadmor, Lebanon OR',
    targetGroup: 'MS + HS students',
    status: 'registration-open',
    parentFacing: true,
    registered: 43,
    capacity: 70,
    volunteers: [
      { role: 'Counselors (male)', needed: 5, confirmed: 4 },
      { role: 'Counselors (female)', needed: 5, confirmed: 4 },
      { role: 'Nurse / medic', needed: 1, confirmed: 1 },
      { role: 'Drivers', needed: 6, confirmed: 6 },
    ],
    forms: 'in-progress',
    payments: 'in-progress',
    transportation: 'complete',
    parentComm: 'in-progress',
    checklist: checklist('summer-camp', [
      ['Camp contract signed + deposit paid', true],
      ['Registration page live', true],
      ['Scholarship fund requests reviewed', true],
      ['Health forms collected (43/43)', false],
      ['Cabin assignments drafted', false],
      ['Packing list sent to parents', true],
      ['Bus + van rental confirmed', true],
      ['Camp store money system decided', false],
    ]),
    clarity: clarity({ foodInfo: false }),
    notes: 'Balance due 2 weeks before departure. 9 students still owe more than half.',
  },
  {
    id: 'mission-trip',
    title: 'Mexico Mission Trip',
    category: 'camps-trips',
    start: day(50, 6, 0),
    location: 'Ensenada, Mexico',
    targetGroup: 'HS students (10th–12th)',
    status: 'planning',
    parentFacing: true,
    registered: 18,
    capacity: 24,
    volunteers: [
      { role: 'Adult leaders', needed: 6, confirmed: 4 },
      { role: 'Construction lead', needed: 1, confirmed: 1 },
    ],
    forms: 'in-progress',
    payments: 'in-progress',
    transportation: 'not-started',
    parentComm: 'not-started',
    checklist: checklist('mission-trip', [
      ['Partner org dates confirmed', true],
      ['Passport check — all students', false],
      ['Support letter template sent', true],
      ['Fundraiser scheduled', false],
      ['Travel insurance quotes', false],
      ['Team training night 1 of 3', false],
    ]),
    clarity: clarity({
      dropOffLocation: false,
      pickUpTime: false,
      foodInfo: false,
      transportation: false,
      packingList: false,
    }),
    notes: 'Passports are the long pole — flag any student without one this month.',
  },
  {
    id: 'potluck',
    title: 'Youth Thanksgiving Potluck',
    category: 'high-school',
    start: day(160, 18, 0),
    location: 'Fellowship Hall',
    targetGroup: 'All students + families',
    status: 'planning',
    parentFacing: true,
    registered: 0,
    volunteers: [{ role: 'Setup / teardown', needed: 4, confirmed: 0 }],
    forms: 'na',
    payments: 'na',
    transportation: 'na',
    parentComm: 'not-started',
    checklist: checklist('potluck', [
      ['Pick date with church calendar', true],
      ['Sign-up sheet for dishes', false],
    ]),
    clarity: clarity({
      time: false,
      dropOffLocation: false,
      pickUpTime: false,
      cost: false,
      foodInfo: false,
      contactPerson: false,
      packingList: false,
    }),
  },
  {
    id: 'dl-camp-earlybird',
    title: 'Camp early-bird rate ends',
    category: 'deadline',
    start: day(8, 17, 0),
    location: '—',
    targetGroup: 'Camp families',
    status: 'confirmed',
    parentFacing: false,
    registered: 0,
    volunteers: [],
    forms: 'na',
    payments: 'na',
    transportation: 'na',
    parentComm: 'in-progress',
    checklist: checklist('dl-camp', [['Final reminder email + text', false]]),
    clarity: clarity({
      dropOffLocation: false,
      pickUpTime: false,
      foodInfo: false,
      transportation: false,
      packingList: false,
    }),
  },
  {
    id: 'dl-mission-deposit',
    title: 'Mission trip deposits due',
    category: 'deadline',
    start: day(14, 17, 0),
    location: '—',
    targetGroup: 'Mission trip families',
    status: 'confirmed',
    parentFacing: false,
    registered: 0,
    volunteers: [],
    forms: 'na',
    payments: 'na',
    transportation: 'na',
    parentComm: 'not-started',
    checklist: checklist('dl-mission', [['Deposit reminder to 18 families', false]]),
    clarity: clarity({
      dropOffLocation: false,
      pickUpTime: false,
      foodInfo: false,
      transportation: false,
      packingList: false,
    }),
  },
  {
    id: 'promo-camp-slides',
    title: 'Camp announcement slides due',
    category: 'promo',
    start: day(3, 12, 0),
    location: 'Sunday services',
    targetGroup: 'Whole church',
    status: 'confirmed',
    parentFacing: false,
    registered: 0,
    volunteers: [],
    forms: 'na',
    payments: 'na',
    transportation: 'na',
    parentComm: 'na',
    checklist: checklist('promo-camp', [
      ['Slide designed', false],
      ['Submitted to comms team', false],
    ]),
    clarity: clarity({
      dropOffLocation: false,
      pickUpTime: false,
      foodInfo: false,
      transportation: false,
      packingList: false,
    }),
  },
  {
    id: 'promo-lakeday-video',
    title: 'Lake Day promo video at youth',
    category: 'promo',
    start: day(7, 19, 0),
    location: 'The Barn',
    targetGroup: 'All students',
    status: 'planning',
    parentFacing: false,
    registered: 0,
    volunteers: [{ role: 'Video editor', needed: 1, confirmed: 0 }],
    forms: 'na',
    payments: 'na',
    transportation: 'na',
    parentComm: 'na',
    checklist: checklist('promo-lake', [
      ['Clips from last year pulled', true],
      ['30-second cut edited', false],
    ]),
    clarity: clarity({
      dropOffLocation: false,
      pickUpTime: false,
      foodInfo: false,
      transportation: false,
      packingList: false,
    }),
  },
];

// ---------- Tasks ----------

export const TASKS: Task[] = [
  { id: 't1', title: 'Send camp payment reminder to 9 families', category: 'communication', due: day(1, 12), done: false, priority: 'urgent', eventId: 'summer-camp' },
  { id: 't2', title: 'Parent newsletter — June edition', category: 'communication', due: day(-1, 17), done: false, priority: 'urgent', notes: 'Overdue — include Lake Day + camp deadlines.' },
  { id: 't3', title: 'Buy snacks for HS youth tonight', category: 'shopping', due: day(0, 16), done: false, priority: 'high', eventId: 'hs-youth' },
  { id: 't4', title: 'Call Marcus about driving for Lake Day', category: 'volunteer-follow-up', due: day(1, 15), done: false, priority: 'high', eventId: 'lake-day' },
  { id: 't5', title: 'Find 2 more camp counselors', category: 'volunteer-follow-up', due: day(5, 17), done: false, priority: 'urgent', eventId: 'summer-camp', notes: 'Pitch at Leader Lunch — one male, one female spot left.' },
  { id: 't6', title: 'Text Eli — missed 3 weeks in a row', category: 'student-care', due: day(0, 14), done: false, priority: 'high' },
  { id: 't7', title: 'Reply to Rosa Alvarez — health form question', category: 'parent-follow-up', due: day(-2, 12), done: false, priority: 'urgent', eventId: 'summer-camp' },
  { id: 't8', title: 'Call the Hendersons re: camp scholarship', category: 'parent-follow-up', due: day(2, 14), done: false, priority: 'high', eventId: 'summer-camp' },
  { id: 't9', title: 'Book vans for Lake Day', category: 'event-prep', due: day(3, 12), done: false, priority: 'high', eventId: 'lake-day' },
  { id: 't10', title: 'Reserve sound system for Tribe Night', category: 'event-prep', due: day(5, 12), done: false, priority: 'normal', eventId: 'tribe-night' },
  { id: 't11', title: 'Costco run — Tribe Night supplies', category: 'shopping', due: day(8, 10), done: false, priority: 'normal', eventId: 'tribe-night' },
  { id: 't12', title: 'Welcome card for Ava (first-time guest)', category: 'student-care', due: day(2, 12), done: false, priority: 'normal' },
  { id: 't13', title: 'Coffee with Noah — baptism conversation', category: 'student-care', due: day(7, 9), done: false, priority: 'high' },
  { id: 't14', title: 'Post Lake Day promo reel', category: 'communication', due: day(4, 12), done: false, priority: 'normal', eventId: 'lake-day' },
  { id: 't15', title: 'Confirm childcare for parent meeting', category: 'volunteer-follow-up', due: day(6, 12), done: true, priority: 'normal', eventId: 'parent-meeting' },
  { id: 't16', title: 'Order Tribe Night color powder', category: 'shopping', due: day(-3, 12), done: true, priority: 'high', eventId: 'tribe-night' },
];

// ---------- People ----------

export const STUDENTS: Student[] = [
  { id: 's1', name: 'Eli Thompson', grade: '9th', group: 'high', school: 'Summit High', smallGroupId: 'g1', needsFollowUp: true, followUpReason: 'Missed 3 weeks in a row', parentIds: ['p1'] },
  { id: 's2', name: 'Noah Garcia', grade: '11th', group: 'high', school: 'Bend High', smallGroupId: 'g1', needsFollowUp: true, followUpReason: 'Asked about baptism after youth group', parentIds: ['p2'] },
  { id: 's3', name: 'Ava Chen', grade: '7th', group: 'middle', school: 'Pilot Butte MS', isNew: true, needsFollowUp: true, followUpReason: 'First-time guest last week — send welcome', parentIds: ['p3'] },
  { id: 's4', name: 'Maddie Brooks', grade: '8th', group: 'middle', school: 'Sky View MS', smallGroupId: 'g4', parentIds: ['p4'] },
  { id: 's5', name: 'Jaylen Carter', grade: '10th', group: 'high', school: 'Mountain View High', smallGroupId: 'g1', parentIds: ['p5'] },
  { id: 's6', name: 'Sophie Nguyen', grade: '12th', group: 'high', school: 'Bend High', smallGroupId: 'g2', needsFollowUp: true, followUpReason: 'Graduating — invite to leader pipeline', parentIds: ['p6'] },
  { id: 's7', name: 'Caleb Martin', grade: '6th', group: 'middle', school: 'Cascade MS', isNew: true, parentIds: [] },
  { id: 's8', name: 'Grace Kim', grade: '9th', group: 'high', school: 'Summit High', smallGroupId: 'g2', parentIds: [] },
  { id: 's9', name: 'Tyler Reed', grade: '8th', group: 'middle', school: 'Pilot Butte MS', smallGroupId: 'g3', needsFollowUp: true, followUpReason: 'Parents separating — check in gently', parentIds: [] },
  { id: 's10', name: 'Lily Foster', grade: '11th', group: 'high', school: 'Summit High', smallGroupId: 'g2', parentIds: [] },
  { id: 's11', name: 'Mia Henderson', grade: '7th', group: 'middle', school: 'Sky View MS', smallGroupId: 'g4', parentIds: ['p7'] },
  { id: 's12', name: 'Diego Alvarez', grade: '10th', group: 'high', school: 'Mountain View High', smallGroupId: 'g1', parentIds: ['p8'] },
];

export const PARENTS: Parent[] = [
  { id: 'p1', name: 'Dana Thompson', studentIds: ['s1'], phone: '(541) 555-0142', email: 'dana.t@example.com', engagement: 'medium' },
  { id: 'p2', name: 'Maria Garcia', studentIds: ['s2'], phone: '(541) 555-0167', email: 'mgarcia@example.com', engagement: 'high' },
  { id: 'p3', name: 'Wendy Chen', studentIds: ['s3'], phone: '(541) 555-0119', email: 'wendy.chen@example.com', engagement: 'low' },
  { id: 'p4', name: 'Rob Brooks', studentIds: ['s4'], phone: '(541) 555-0188', email: 'rbrooks@example.com', engagement: 'high' },
  { id: 'p5', name: 'Tasha Carter', studentIds: ['s5'], phone: '(541) 555-0173', email: 'tasha.c@example.com', engagement: 'medium' },
  { id: 'p6', name: 'Kim Nguyen', studentIds: ['s6'], phone: '(541) 555-0151', email: 'kim.nguyen@example.com', engagement: 'high' },
  { id: 'p7', name: 'Paul Henderson', studentIds: ['s11'], phone: '(541) 555-0136', email: 'phenderson@example.com', engagement: 'medium' },
  { id: 'p8', name: 'Rosa Alvarez', studentIds: ['s12'], phone: '(541) 555-0194', email: 'rosa.alvarez@example.com', engagement: 'high' },
];

export const LEADERS: Leader[] = [
  { id: 'l1', name: 'Marcus Lee', role: 'HS small group leader', assignments: ['HS Guys group', 'Lake Day driver (unconfirmed)'], backgroundCheck: 'clear' },
  { id: 'l2', name: 'Rachel Park', role: 'MS coordinator', assignments: ['MS Girls group', 'Camp counselor'], backgroundCheck: 'clear' },
  { id: 'l3', name: 'Dave Olsen', role: 'Games + grill', assignments: ['MS Boys group', 'Lake Day grill'], backgroundCheck: 'expired' },
  { id: 'l4', name: 'Hannah Wright', role: 'Worship lead', assignments: ['Youth band'], backgroundCheck: 'clear' },
  { id: 'l5', name: 'Sam Otieno', role: 'Check-in team', assignments: ['Wednesday check-in'], backgroundCheck: 'pending' },
  { id: 'l6', name: 'Becca Liu', role: 'HS small group leader', assignments: ['HS Girls group', 'Camp counselor'], backgroundCheck: 'clear' },
  { id: 'l7', name: 'Katie Moore', role: 'Parent comms volunteer', assignments: ['Newsletter help'], backgroundCheck: 'clear' },
];

export const SMALL_GROUPS: SmallGroup[] = [
  { id: 'g1', name: 'HS Guys — Lee', leaderId: 'l1', meetingNight: 'Wednesday', studentIds: ['s1', 's2', 's5', 's12'] },
  { id: 'g2', name: 'HS Girls — Liu', leaderId: 'l6', meetingNight: 'Wednesday', studentIds: ['s6', 's8', 's10'] },
  { id: 'g3', name: 'MS Boys — Olsen', leaderId: 'l3', meetingNight: 'Thursday', studentIds: ['s9'] },
  { id: 'g4', name: 'MS Girls — Park', leaderId: 'l2', meetingNight: 'Thursday', studentIds: ['s4', 's11'] },
];

// ---------- Event templates ----------

const PARENT_FACING_FIELDS: (keyof ClarityInfo)[] = [
  'date', 'time', 'dropOffLocation', 'pickUpTime', 'cost',
  'foodInfo', 'forms', 'contactPerson', 'transportation', 'packingList',
];

export const TEMPLATES: EventTemplate[] = [
  {
    id: 'tpl-weekly',
    parentFacing: true,
    name: 'Weekly Youth Group',
    description: 'The weekly rhythm — message, worship, games, small groups.',
    category: 'high-school',
    leadTimeWeeks: 1,
    defaultChecklist: ['Message prepped', 'Worship set confirmed', 'Game planned + supplies', 'Snacks purchased', 'Small group questions to leaders', 'Check-in team confirmed'],
    clarityFields: ['date', 'time', 'dropOffLocation', 'pickUpTime', 'contactPerson'],
    typicalVolunteers: ['Check-in (2)', 'Small group leaders (4–6)', 'Snack team (2)'],
  },
  {
    id: 'tpl-camp',
    parentFacing: true,
    name: 'Camp',
    description: 'Multi-day overnight camp. The biggest lift of the year.',
    category: 'camps-trips',
    leadTimeWeeks: 16,
    defaultChecklist: ['Camp contract + deposit', 'Registration page live', 'Health + liability forms', 'Scholarship process', 'Counselor recruitment', 'Cabin assignments', 'Transportation booked', 'Packing list to parents', 'Payment deadlines communicated', 'Emergency contact sheet printed'],
    clarityFields: PARENT_FACING_FIELDS,
    typicalVolunteers: ['Counselors (1 per 6 students)', 'Nurse/medic (1)', 'Drivers (4–8)'],
  },
  {
    id: 'tpl-retreat',
    parentFacing: true,
    name: 'Retreat',
    description: 'Weekend getaway — lighter than camp, same parent-info needs.',
    category: 'camps-trips',
    leadTimeWeeks: 10,
    defaultChecklist: ['Venue booked', 'Registration live', 'Forms collected', 'Speaker/curriculum chosen', 'Meal plan', 'Transportation plan', 'Packing list sent'],
    clarityFields: PARENT_FACING_FIELDS,
    typicalVolunteers: ['Cabin leaders', 'Kitchen team', 'Drivers'],
  },
  {
    id: 'tpl-lake-day',
    parentFacing: true,
    name: 'Lake Day',
    description: 'Single-day water event. Waivers and supervision are the big rocks.',
    category: 'camps-trips',
    leadTimeWeeks: 6,
    defaultChecklist: ['Site/permit reserved', 'Liability waivers posted', 'Driver list + insurance', 'Lifeguard coverage', 'Food plan', 'Sunscreen + first aid', 'Parent info email'],
    clarityFields: PARENT_FACING_FIELDS,
    typicalVolunteers: ['Drivers (6–10)', 'Lifeguard-certified adults (2)', 'Grill team (2)'],
  },
  {
    id: 'tpl-parent-meeting',
    parentFacing: true,
    name: 'Parent Meeting',
    description: 'Info night for parents — slides, FAQ handout, childcare.',
    category: 'parents',
    leadTimeWeeks: 4,
    defaultChecklist: ['Date on church calendar', 'Slide deck', 'FAQ handout printed', 'RSVP form', 'Childcare arranged', 'Reminder email + text'],
    clarityFields: ['date', 'time', 'contactPerson'],
    typicalVolunteers: ['Childcare (2)'],
  },
  {
    id: 'tpl-leader-meeting',
    parentFacing: false,
    name: 'Leader Meeting',
    description: 'Vision, calendar, and care for your volunteer team.',
    category: 'leaders',
    leadTimeWeeks: 2,
    defaultChecklist: ['Agenda drafted', 'Food ordered', 'Calendar handout', 'One appreciation moment planned'],
    clarityFields: ['date', 'time', 'contactPerson'],
    typicalVolunteers: [],
  },
  {
    id: 'tpl-service-project',
    parentFacing: true,
    name: 'Service Project',
    description: 'Hands-on serve day with a local partner organization.',
    category: 'high-school',
    leadTimeWeeks: 5,
    defaultChecklist: ['Partner org confirmed', 'Waivers if off-site', 'Supplies list', 'Transportation plan', 'Parent email with details'],
    clarityFields: PARENT_FACING_FIELDS,
    typicalVolunteers: ['Adult leaders (1 per 8)', 'Drivers'],
  },
  {
    id: 'tpl-fundraiser',
    parentFacing: true,
    name: 'Fundraiser',
    description: 'Raise money for camp or missions — clear goal, clear ask.',
    category: 'promo',
    leadTimeWeeks: 6,
    defaultChecklist: ['Goal + use of funds defined', 'Date on church calendar', 'Promo plan (announcement, slides, social)', 'Student sign-ups', 'Cash handling plan', 'Thank-you follow-up'],
    clarityFields: ['date', 'time', 'cost', 'contactPerson'],
    typicalVolunteers: ['Setup team', 'Cash handlers (2 adults)'],
  },
  {
    id: 'tpl-tribe-night',
    parentFacing: true,
    name: 'Tribe Night',
    description: 'High-energy competition night. Bring-a-friend culture builder.',
    category: 'high-school',
    leadTimeWeeks: 4,
    defaultChecklist: ['Tribe rosters', 'Station games chosen', 'Supplies purchased', 'Promo video', 'Station leaders briefed', 'Prizes'],
    clarityFields: ['date', 'time', 'dropOffLocation', 'pickUpTime', 'foodInfo', 'contactPerson'],
    typicalVolunteers: ['Station leaders (6)', 'Check-in (2)', 'Photographer (1)'],
  },
  {
    id: 'tpl-bible-study',
    parentFacing: false,
    name: 'Bible Study',
    description: 'Recurring deep-dive study, usually off-campus.',
    category: 'bible-study',
    leadTimeWeeks: 2,
    defaultChecklist: ['Passage/curriculum chosen', 'Location reserved', 'Reading plan sent', 'Co-leader confirmed'],
    clarityFields: ['date', 'time', 'contactPerson'],
    typicalVolunteers: ['Co-leader (1)'],
  },
  {
    id: 'tpl-mission-trip',
    parentFacing: true,
    name: 'Mission Trip',
    description: 'The longest runway in youth ministry — passports, funds, training.',
    category: 'camps-trips',
    leadTimeWeeks: 26,
    defaultChecklist: ['Partner org + dates confirmed', 'Interest meeting', 'Passport check', 'Deposit schedule', 'Support letter template', 'Fundraisers scheduled', 'Team training nights (3)', 'Travel insurance', 'Emergency protocol + contacts', 'Commissioning Sunday'],
    clarityFields: PARENT_FACING_FIELDS,
    typicalVolunteers: ['Adult leaders (1 per 4)', 'Trip nurse', 'Prayer team'],
  },
  {
    id: 'tpl-graduation',
    parentFacing: true,
    name: 'Graduation Night',
    description: 'Honor the seniors — slideshow, blessings, send-off.',
    category: 'high-school',
    leadTimeWeeks: 6,
    defaultChecklist: ['Senior list confirmed', 'Photo slideshow', 'Leader blessing assignments', 'Gifts ordered', 'Parent invitations', 'Dessert plan'],
    clarityFields: ['date', 'time', 'foodInfo', 'contactPerson'],
    typicalVolunteers: ['Slideshow editor', 'Dessert team'],
  },
];
